### ISSUE TITLE
[4/23] Design and Planning Document

### ISSUE THREAD

**Issue by ldm2468** [2019-swpp-8/swpp#11]
Design and Planning Document를 4/23까지 제출해야 합니다.
조교님이 올리신 예시: https://github.com/snu-sf-class/swpp201901/blob/master/project-examples/SWPP_PlainPlane_Design_and_Planning.pdf

**Comment by ldm2468** [comment]
[여기에 작성해 주세요!](https://github.com/2019-swpp-8/swpp/wiki/Design-and-Planning-Document)

**Comment by joh16** [comment]
Sprint 1 현황까지 작성하였습니다. 피드백이 있다면 덧글을 달아주세요!

**Comment by ldm2468** [comment]
제출 완료했습니다!
