### ISSUE TITLE
데이터베이스에 Array 저장하기 (models.py)

### ISSUE THREAD

**Issue by joh16** [2019-swpp-8/swpp#20]
Backend 구현에 있어 model이랑 serializer 쪽 파일들 건드리려고 보니까 모델이 갖는 속성에 list(array)가 상당 수 보이는데, 기본 데이터베이스인 SQLite3에는 list를 직접 편안하게 저장할 방법이 마땅히 없더군요.

구체적으로는 Tutor에서 lectures(들은 강의들)와 times(시간대), Profile에서 tags(관심 분야)와 requests(튜터링 내역) 속성은 list로 구현되어야 하는데, 검색을 좀 해보니까 PostgresSQL? 쓰면 ArrayField가 지원된다고 하고, 아니면 CharField 등에 comma 등의 구분기호를 넣어 저장하고 꺼내올 때 가공하는 것도 방법인듯 합니다.

어떻게 구현하는게 좋을까요?

**Comment by ldm2468** [comment]
아무래도 PostgreSQL이나 MySQL/MariaDB같은 데이터베이스 서비스를 따로 사용하게 되면 deploy하거나 test하기 번거로울 것 같아서 SQLite를 쓰는게 좋을 것 같습니다.

찾아보니 SQLite 내부 변수 종류는 `SQLITE_INTEGER`, `SQLITE_FLOAT`, `SQLITE_BLOB`, `SQLITE_TEXT`가 전부인 것 같으니 `SQLITE_BLOB`에 대응되는 `BinaryField` 또는 `SQLITE_TEXT`에 대응되는 `CharField`를 사용하는 것이 알맞을 것 같습니다.

**Comment by ldm2468** [comment]
특히 List 등 python 변수를 binary로 serialize하는 방법을 알아보면 도움이 될 듯 합니다.
ex) https://docs.python.org/3/library/pickle.html

**Comment by ldm2468** [comment]
정 힘들다면 JSON으로 encode하고 CharField에 때려박는것도 가능한 방법입니다.

**Comment by joh16** [comment]
ManyToMany, ForeignKey field를 적절히 사용하여 해결하였습니다. 조언 감사합니다.
