### ISSUE TITLE
[중요] Iteration 2 Pull Request 마감: ~5/6(월) 8PM

### ISSUE THREAD

**Issue by ldm2468** [2019-swpp-8/swpp#26]
Iteration 2는 5/6 자정까지입니다.

마감시간 전까지 코드리뷰를 마치고 Progress Report를 작성해야하므로,
Pull Request를 **5월 6일 오후 8시까지** 올려야 합니다.

그 후에 올리는 것은 Iteration 2 Progress Report에 반영되지 않을 것입니다.

**Comment by joh16** [comment]
https://github.com/snu-sf-class/swpp201901/issues/48

Report 작성시에 참고하시기 바랍니다.
