### ISSUE TITLE
Profile 모델의 serializer가 partial update를 지원하지 않음

### ISSUE THREAD

**Issue by ldm2468** [2019-swpp-8/swpp#29]
Profile 모델의 serializer validate() 함수가 partial update를 지원하지 않습니다.
예를 들어, PUT request에서 전화번호가 수정되지 않은 경우에 에러가 납니다.
`backend/swpp/serializer/profile.py`에서 `data.get('contact')`하기 전에 contact 필드가 존재하는지 확인해보면 될 것 같습니다.

**Comment by joh16** [comment]
음, 전화번호가 비어 있는 상태로 냅두며 partial update를 하는 경우를 허용해야 할 지 모르겠지만, 그래도 partial update는 지원할 수 있도록 곧 수정하여 pull request 생성하도록 하겠습니다.

**Comment by ldm2468** [comment]
허용하지 않는건 괜찮지만 지금처럼 서버가 터지는건 좋지 않습니다.

**Comment by j2kim99** [comment]
전화번호가 비어 있는 상황을 시스템 전체에서 전혀 허용하지 않고
유저가 가입할 때 꼭 전화번호를 넣게 한다면
아예 프로파일이 자동생성될 때 형식에 맞는 전화번호가 디폴트로 들어가게 하면 될 것 같습니다.
우선 그렇게 수정한 브랜치 하나 올려두었습니다.

**Comment by ldm2468** [comment]
@j2kim99 깔끔한 해결 방법이네요. 테스트해보니까 잘 되는 것 같아요!
Pull request 올려주세요!
