### ISSUE TITLE
시간대 비교 기능 구현

### ISSUE THREAD

**Issue by ldm2468** [2019-swpp-8/swpp#38]
64비트 정수 7개로 나타낸 시간대 변수를 비교하는 기능을 구현해야합니다.
(겹치는 시간이 있는지, 있다면 몇 시간 겹치는지)
이걸 구현해야지 검색 기능을 제대로 완료할 수 있습니다.

**Comment by joh16** [comment]
https://github.com/2019-swpp-8/swpp/pull/47

시간대를 이용한 튜터 검색이 가능하도록 하였습니다
