### ISSUE TITLE
Frontend 시간대 확인/수정 인터페이스 구현

### ISSUE THREAD

**Issue by ldm2468** [2019-swpp-8/swpp#39]
정수형 시간대 정보를 보기 좋게 시간표 형식으로 표현하고, 수정할 수 있어야 합니다.
(스랖 강의실+에서 강의 검색할 때 시간대 필터링하는 인터페이스를 참고하면 좋을 것 같습니다.)
이 기능이 완료되어야 frontend 튜터 정보 기능을 제대로 구현할 수 있습니다.

**Comment by joh16** [comment]
https://github.com/2019-swpp-8/react-week-scheduler

좋은 라이브러리를 찾아서 fork했고, 15분이 기본단위였던 것을 30분으로 @ldm2468  이 수정하였습니다. @j2kim99 님이 이걸 맡게 되시면 이 라이브러리에서 3가지 색깔 중 노란색(limit) 옵션을 삭제하고, 나머지의 이름을 가능, 불가능 으로 바꾸면 저희 프로젝트에 적용할 수 있을 것 같습니다. Redux 부분까지 구현해서 backend와 연동까지 하면 시간대를 이용한 검색 및 튜터 프로필에서 시간대 편집이 완료되겠습니다.
