### ISSUE TITLE
수강신청 사이트 크롤링

### ISSUE THREAD

**Issue by joh16** [2019-swpp-8/swpp#53]
곧 Lecture를 기준으로 한 검색 기능을 구현해야 하는데, 그 전에 먼저 수강신청 사이트로부터 과목의 목록을 받아와서 데이터베이스를 구축하는 게 선행되어야 할 것 같습니다.

**Comment by joh16** [comment]
[강좌검색.zip](https://github.com/2019-swpp-8/swpp/files/3226013/default.zip)

수강신청 사이트에서 상세검색에 학기만 넣고 다른 옵션은 건드리지 않은 채 검색한 후 엑셀저장을 누르면 해당 학기의 모든 과목 데이터를 엑셀로 다운로드 할 수 있습니다.

**Comment by joh16** [comment]
2012년부터 모든 학기의 엑셀파일을 다운로드하고, 파일을 parsing하여 (교과목명, 주담당교수) 항목들을 겹치지 않게 처리한 데이터베이스를 구축하는 코드를 짜고 있습니다. 굳이 웹 크롤링 없이도 데이터베이스 확보가 가능할 것 같네요.

**Comment by ldm2468** [comment]
#56 으로 해결
