### ISSUE TITLE
Tag 모델 삭제?

### ISSUE THREAD

**Issue by joh16** [2019-swpp-8/swpp#68]
이미 경력과 자기소개, 과목으로 검색을 할 수 있는 시점에서 Tag가 꼭 필요한 기능인지 의문입니다.

시간 문제도 있고, 중요도도 떨어지는 듯 하여 해당 기능을 삭제하는 게 어떨까요?

**Comment by ldm2468** [comment]
네 굳이 tag는 구현 난이도에 비해 얻는 이득이 적다고 생각합니다.

**Comment by joh16** [comment]
다음 commit 시에 삭제하도록 하겠습니다!
